INTRODUCTION

In [1]:
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[4,5,6,7,8,9,10]],dtype='int32')
b=np.array([[1,2,3,4,5,6,7,],[4,5,6,7,8,9,10]],dtype='int32')
print(a*b)
print(a.ndim) # gives the dimensions of the array (1,2,3)
print(b.ndim)
print(a.shape) #gives the size of the array
print(a.dtype)
print(b.dtype) #get the size
print(a.itemsize) # gives the memory size (ex:int8=1byte)
print(a.nbytes) # gives the total memory(nitem * nitemsize) 

[[  1   4   9  16  25  36  49]
 [ 16  25  36  49  64  81 100]]
2
2
(2, 7)
int32
int32
4
56


ACCESSSING & CHANGING ELEMENT 

In [20]:
# can use [r,c] .For continuous value we use ":" & for discreate value we use ","
print(a[1,5]) #  then the output is 6
print(a[1,-1]) # then the same output
print(a[1,:]) # getting the specific row 
print(a[:,5])# getting the specific column 
print(a[0,1:6]) #this is equal to the slicing method
print(a[0,1:6:2]) # this gives the same above output but with the increment of 2 & print(a[:,1:2:2]) is for column
a[1,5]=5 # changes the number from 9:5
a[:,4]=9 # changes the number to 9 in both original will be altered
print(a) 
a[1,:]=7
print(a)

5
10
[ 4  5  6  7  9  5 10]
[6 5]
[2 3 4 9 6]
[2 4 6]
[[ 1  2  3  4  9  6  7]
 [ 4  5  6  7  9  5 10]]
[[1 2 3 4 9 6 7]
 [7 7 7 7 7 7 7]]


ACCSESSING & CHANGING OF 3-D ELEMENT

In [5]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
print(c.ndim) # gives the dimensions of the array (1,2,3)
print(c.shape) #gives the size of the array
print(c.dtype) 
print(c.itemsize) # gives the memory size (ex:int8=1byte)
print(c.nbytes) # gives the total memory(nitem * nitemsize) 
#getting the specific element(working:outside end [outside to inside])
print(c[0,1,1]) # perforrming from outside of opening the bracket
print(c[:,1,:]) # row-wise
print(c[:,:,0]) #column-wise
c[:,1,:]=[[9,9],[10,10]]
print(c) # updates

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)
int64
8
64
4
[[3 4]
 [7 8]]
[[1 3]
 [5 7]]
[[[ 1  2]
  [ 9  9]]

 [[ 5  6]
  [10 10]]]


WORKING WITH IN-BULLT FUNCTIONS

In [6]:
arr=np.zeros(5) #in intialaize all element to 0
print(arr)
arr=np.zeros((2,3),dtype='float16') # we should give the shape of the required matrix 
print(arr)
arr2=np.ones((1,3,5),dtype='int32') # similar to the zeroes
print(arr2)
#initialzing the array other than 0's & 1's
arr3=np.full((2,3),5,dtype='float32') # 2 parametres- 1)shape & 2)required no 
print(arr3)
arr4=np.full((a.shape),5) 
print(arr4)
arr5=np.full_like(a,9)
print(arr5)
arr6=np.random.rand(2,4) # giving the shape of desired array inside parenthesis & generates random decimal
print(arr6)
arr7=np.random.random_sample(a.shape) # takes the shape of array 'a' 
print(arr7)
arr8=np.random.randint(0,9,size=(2,3)) #  inside parenthesis (start,stop,size)
print(arr8) 
print(np.identity(3)) # identity matrices of 3 i.e=3*3 
# array repetiting
arr9=np.repeat(arr8,3,axis=0) # inside parenthesis (array,repetation required,axis)
print(arr9)
ar9=np.repeat(arr8,3,axis=1) 
print(ar9)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5]]
[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]
[[0.96014529 0.62194759 0.1962557  0.48407183]
 [0.47178188 0.65584745 0.22205754 0.14392927]]
[[0.07134822 0.1483604  0.49912051 0.51752748 0.68245438 0.95766743
  0.31527584]
 [0.19612548 0.4105968  0.24803324 0.9934939  0.03867318 0.51565458
  0.00211472]]
[[6 2 2]
 [8 3 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[6 2 2]
 [6 2 2]
 [6 2 2]
 [8 3 0]
 [8 3 0]
 [8 3 0]]
[[6 6 6 2 2 2 2 2 2]
 [8 8 8 3 3 3 0 0 0]]


PROBLEM 1: OF GETTING THE MATRICES

In [7]:
array=np.ones((5,5),dtype='int32')
print(array)
zero=np.zeros((3,3),dtype='int32')
print(zero)
zero[1,1]=9
print(zero)
array[1:4,1:4]=zero
print("array:\n",array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 9 0]
 [0 0 0]]
array:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


BASIC MATHEMATICS

In [8]:
d=np.array([1,2,3,4])
print(d+2)
print(d-2)
print(d*2)
print(d/2)
print(d**2)
print(np.sin(d)) # gives sin values
print(np.tan(d)) # gives tan values

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


LINEAR ALZEBRA

In [9]:
v=np.ones((2,3))
z=np.full((3,3),2)
print(np.matmul(v,z)) # as v*z fails so we use matrice mutltiplication technique (2,3) &(3,2)
print(np.linalg.det(z))
eigen_values,eigen_vectors=np.linalg.eig(z)
print("Values",eigen_values)
print("Vectors",eigen_vectors)

[[6. 6. 6.]
 [6. 6. 6.]]
0.0
Values [-4.44089210e-16+0.j  6.00000000e+00+0.j -4.20553974e-33+0.j]
Vectors [[-8.16496581e-01+0.j  5.77350269e-01+0.j -1.47578704e-18+0.j]
 [ 4.08248290e-01+0.j  5.77350269e-01+0.j -7.07106781e-01+0.j]
 [ 4.08248290e-01+0.j  5.77350269e-01+0.j  7.07106781e-01+0.j]]


STATISTICS

In [22]:
stats=np.array([[1,2,3],[4,5,6]])
print(np.min(stats)) # finding minimum
print(np.max(stats)) # finding maximum
print(np.min(stats,axis=1)) # finding row-wise
print(np.max(stats,axis=1)) # finding row-wise
print(np.mean(stats)) # finding mean
print(np.mean(stats,axis=1)) # finding row-wise
print(np.sum(stats)) # addition
print(np.sum(stats,axis=1)) # row-wise addition

1
6
[1 4]
[3 6]
3.5
[2. 5.]
21
[ 6 15]


RE-ORGANISING THE ARRAY'S

In [32]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)
after=before.reshape((8,1)) # reshaping or we can give(2,2,2) should be 8 not more or less
print(after) 
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack([v1,v2])) #vertically stacking 
print(np.vstack([v1,v2,v1,v2,v2,v1]))
print(np.hstack([v1,v2])) # horizontal stack
print(np.hstack([v1,v2,v1,v2,v2]))

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8 5 6 7 8]


ADVANCED INDEXING

In [38]:
array1=np.array([[2,3,4,5],[1,2,3,4]])
print(array1>5) # RETURNS BOOLEAN TYPE AS ANSWER
print(array1[array1>3]) # returns only the numbers greater than given condition 
print(array1[array1>3]==0)  # gives the Boolean number

[[False False False False]
 [False False False False]]
[4 5 4]
[False False False]
