Reshaping

In [8]:
import numpy as np

In [9]:
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)  # converts to the 1-d array
print(newarr)

[1 2 3 4 5 6]


iterating through array


In [10]:
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [11]:
arr=np.array([1,2,3,4,5,6])
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')


In [13]:
arr=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr[:,::2]): #take all row & column with printing by skiping the index by 2
    print(i)

1
3
4
6


array concantenation


In [17]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
final_arr=np.concatenate((arr1,arr2)) #its converts to multi-dimensional array
print("without Axis is :",final_arr)
final_arr2=np.concatenate((arr1,arr2),axis=0)
print("Axis with 0 is :",final_arr2)
final_arr3=np.concatenate((arr1,arr2),axis=1)
print("Axis with 1 is :",final_arr3)

without Axis is : [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Axis with 0 is : [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Axis with 1 is : [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
stacking is: [[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]


In [21]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([7,8,9,10,11,12])
stacking=np.stack((arr1,arr2),axis=1)
print("stacking is:",stacking)

stacking is: [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
