Data distribution in python

In [2]:
import numpy as np

In [8]:
a=np.random.choice([1,2,3,7,9],p=[0.0,0.2,0.2,0.5,0.1],size=(3,5)) #p is the probability og getting the correspondence number of the array in the original array & probability sum must be 1
print("The number generated through random module & probability:\n",a)

The number generated through random module & probability:
 [[2 9 7 2 7]
 [3 2 2 2 2]
 [7 2 7 9 9]]


Shuffle & permutations

In [11]:
# Shuffle and permutations leads to the same working & almost same output but the main difference is Shuffle
# alters the main array but permutations leaves the original array in-tact
a=np.array([1,2,3,7,9])
np.random.shuffle(a)
print("the array after shuffle of 1-D array:\n",a)
arr=np.array([[1,2,9],[4,7,6],[3,8,9]])
np.random.shuffle(arr)
print("The array after shuffle of 2-D array:\n",arr)
print("The permutations of the 1-D array:\n",np.random.permutation(a))
print("The permutations of the 2-D array:\n",np.random.permutation(arr))

the array after shuffle of 1-D array:
 [1 3 9 2 7]
The array after shuffle of 2-D array:
 [[4 7 6]
 [1 2 9]
 [3 8 9]]
The permutations of the 1-D array:
 [9 1 7 2 3]
The permutations of the 2-D array:
 [[3 8 9]
 [1 2 9]
 [4 7 6]]
