Array splitting


In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr2=np.array_split(arr,5) # arr is the array wanted to be splitted & 5 is the no of spllitting
print("Array splitted by 5:",arr2)
arr3=np.array_split(arr,4)
print("Array splitted by 4:",arr3)
print("the splitted array Type is:",type(arr2))
print("the spliited array's item at 0 index is:",arr3[0])

Array splitted by 5: [array([1]), array([2]), array([3]), array([4]), array([5])]
Array splitted by 4: [array([1, 2]), array([3]), array([4]), array([5])]
the splitted array Type is: <class 'list'>
the spliited array's item at 0 index is: [1 2]


In [3]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array_split(arr,3)
print("2-D Array splitted by 3:",arr2)
arr3=np.array_split(arr,3,axis=1)
print("2-D Array splitted by 3 with axis 1 :",arr3)
arr4=np.hsplit(arr,3)
print("2-D Array splitted horizontally :",arr4)

2-D Array splitted by 3: [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
2-D Array splitted by 3 with axis 1 : [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
2-D Array splitted horizontally : [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


Searching in numpy array

In [4]:
arr=np.array([1,2,3,4,5,6])
arr2=np.where(arr%2==1) #gives the index of the value
print("finding from the where function:",arr2)
arr3=np.searchsorted(arr,4)
print("the number 4 searched using Searching sorted:",arr3)


finding from the where function: (array([0, 2, 4]),)
the number 4 searched using Searching sorted: 3


Filtering of an array

In [5]:
arr=np.array([1,2,3,4,5,6])
x=[True,False,False,True,True,False]
newarr=arr[x]
print("the element that is having 'true' as a value:",newarr)

the element that is having 'true' as a value: [1 4 5]


Random module in numpy

In [6]:
a=np.random.randint(100)
b=[]
print("random module in Numpy:",a)
for i in range(10):
    a=np.random.random_sample()
    b.append(a)
print(b)
c=np.random.randint(5,19,size=(2,3,5))
print("array with random numbers using random module is:\n",c)
d=np.random.choice(["A","B","C","D","E","F"],size=(3,5))
print("array with given choice and random module is:\n",d)

random module in Numpy: 48
[0.9741351282250978, 0.8377051661666421, 0.10697186985751783, 0.8487167709864052, 0.861641526700313, 0.7955141958905126, 0.3774826178817383, 0.8961605877887354, 0.12246626738782995, 0.4733782528383047]
array with random numbers using random module is:
 [[[ 6 16 18 14 18]
  [17  7 13  5 18]
  [ 9 10  5 13 14]]

 [[ 5  7 18 15 12]
  [17 11 11  7 14]
  [ 8 12 10  6 17]]]
array with given choice and random module is:
 [['F' 'D' 'F' 'C' 'E']
 ['B' 'B' 'E' 'A' 'D']
 ['B' 'A' 'B' 'D' 'A']]
